#!/bin/bash -e

JOB_NAME=varnish
#root bosh agent dir
BASE_DIR=/var/vcap
SYS_DIR=$BASE_DIR/sys
#Dir for creating pid files
RUN_DIR=$SYS_DIR/run/$JOB_NAME
PIDFILE=$RUN_DIR/$JOB_NAME.pid

#Dir for logging process inf
LOG_DIR=$SYS_DIR/log/$JOB_NAME
JOB_DIR=$BASE_DIR/jobs/$JOB_NAME

CONFIG_DIR=$JOB_DIR/etc
CONFIG_FILE=$CONFIG_DIR/varnish_default.vcl

mkdir -p $RUN_DIR $LOG_DIR $CONFIG_DIR

case $1 in

  start)
    #Enable monit control over process launch
    $BASE_DIR/packages/varnish/sbin/$JOB_NAME -a :6661 -T :6662 -f $CONFIG_FILE && pid $PIDFILE
    ;;
  stop)
    #Enable monit control over process kill
    kill $(cat $PIDFILE)
    ;;
  *)
    echo "Usage: varnish_ctl {start|stop}"
    ;;
esac
